server:
  port: 8084

spring:
  application:
    name: auth-service
  r2dbc:
    url: r2dbc:h2:mem:///authdb
    username: sa
    password:
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  main:
    web-application-type: reactive
  security:
    jwt:
      secret: "MyVeryLongSecretKeyForJWTThatIsAtLeast32Chars"
      expiration: 3600000  # Expiration en millisecondes (1h)



springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

